//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adrenaline.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adrenaline.Strings.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adrenaline.
        /// </summary>
        internal static string MainForm {
            get {
                return ResourceManager.GetString("MainForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        internal static string MainForm_ActivatedMainNotifyIconToolStripMenuItem {
            get {
                return ResourceManager.GetString("MainForm_ActivatedMainNotifyIconToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string MainForm_ExitMainNotifyIconToolStripMenuItem {
            get {
                return ResourceManager.GetString("MainForm_ExitMainNotifyIconToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Enter a key].
        /// </summary>
        internal static string MainForm_KeyInputButton {
            get {
                return ResourceManager.GetString("MainForm_KeyInputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key to be pressed:.
        /// </summary>
        internal static string MainForm_KeyInputLabel {
            get {
                return ResourceManager.GetString("MainForm_KeyInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application will simulate a key press on your keyboard.
        ///
        ///Your computer stays awake and your programs running..
        /// </summary>
        internal static string MainForm_MainLabel {
            get {
                return ResourceManager.GetString("MainForm_MainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click on this icon to reopen the application. Right-click to see more actions..
        /// </summary>
        internal static string MainForm_MainNotifyIcon_BalloonTipText {
            get {
                return ResourceManager.GetString("MainForm_MainNotifyIcon_BalloonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a &quot;beep&quot; sound..
        /// </summary>
        internal static string MainForm_MakeSoundCheckBox {
            get {
                return ResourceManager.GetString("MainForm_MakeSoundCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize timer by ±10%..
        /// </summary>
        internal static string MainForm_RandomIntervalCheckBox {
            get {
                return ResourceManager.GetString("MainForm_RandomIntervalCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (reset).
        /// </summary>
        internal static string MainForm_ResetLinkLabel {
            get {
                return ResourceManager.GetString("MainForm_ResetLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display options..
        /// </summary>
        internal static string MainForm_ShowOptionsCheckBox {
            get {
                return ResourceManager.GetString("MainForm_ShowOptionsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show options.
        /// </summary>
        internal static string MainForm_ShowOptionsMainNotifyIconToolStripMenuItem {
            get {
                return ResourceManager.GetString("MainForm_ShowOptionsMainNotifyIconToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string MainForm_StartStopButton_Start {
            get {
                return ResourceManager.GetString("MainForm_StartStopButton_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string MainForm_StartStopButton_Stop {
            get {
                return ResourceManager.GetString("MainForm_StartStopButton_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send signal to keep device awake..
        /// </summary>
        internal static string MainForm_StayAwakeCheckBox {
            get {
                return ResourceManager.GetString("MainForm_StayAwakeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H&apos;h&apos; mm&apos;m&apos; ss&apos;s&apos;.
        /// </summary>
        internal static string MainForm_TimeInputDateTimePicker {
            get {
                return ResourceManager.GetString("MainForm_TimeInputDateTimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each (interval):.
        /// </summary>
        internal static string MainForm_TimeInputLabel {
            get {
                return ResourceManager.GetString("MainForm_TimeInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application title:.
        /// </summary>
        internal static string MainForm_TitleLabel {
            get {
                return ResourceManager.GetString("MainForm_TitleLabel", resourceCulture);
            }
        }
    }
}
