//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adrenaline.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adrenaline.Strings.es", typeof(es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adrenaline.
        /// </summary>
        internal static string MainForm {
            get {
                return ResourceManager.GetString("MainForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activado.
        /// </summary>
        internal static string MainForm_ActivatedMainNotifyIconToolStripMenuItem {
            get {
                return ResourceManager.GetString("MainForm_ActivatedMainNotifyIconToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string MainForm_ExitMainNotifyIconToolStripMenuItem {
            get {
                return ResourceManager.GetString("MainForm_ExitMainNotifyIconToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Introduce una tecla].
        /// </summary>
        internal static string MainForm_KeyInputButton {
            get {
                return ResourceManager.GetString("MainForm_KeyInputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecla que se debe presionar:.
        /// </summary>
        internal static string MainForm_KeyInputLabel {
            get {
                return ResourceManager.GetString("MainForm_KeyInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta aplicación simulará presionar una tecla en su teclado.
        ///
        ///Su computadora se mantiene activa y sus programas en ejecución..
        /// </summary>
        internal static string MainForm_MainLabel {
            get {
                return ResourceManager.GetString("MainForm_MainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo simular la presión de una tecla. ¿Has bloqueado tu dispositivo?.
        /// </summary>
        internal static string MainForm_MainNotifyIcon_ErrorTipText {
            get {
                return ResourceManager.GetString("MainForm_MainNotifyIcon_ErrorTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haga doble clic en este ícono para reabrir la aplicación. Haz clic derecho para ver más acciones. No bloquees tu dispositivo..
        /// </summary>
        internal static string MainForm_MainNotifyIcon_StartTipText {
            get {
                return ResourceManager.GetString("MainForm_MainNotifyIcon_StartTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Adrenaline se detuvo automáticamente..
        /// </summary>
        internal static string MainForm_MainNotifyIcon_StopTipText {
            get {
                return ResourceManager.GetString("MainForm_MainNotifyIcon_StopTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haz un sonido de &quot;bip&quot;..
        /// </summary>
        internal static string MainForm_MakeSoundCheckBox {
            get {
                return ResourceManager.GetString("MainForm_MakeSoundCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aleatorizar el temporizador en ±10%..
        /// </summary>
        internal static string MainForm_RandomIntervalCheckBox {
            get {
                return ResourceManager.GetString("MainForm_RandomIntervalCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (restaurar).
        /// </summary>
        internal static string MainForm_ResetLinkLabel {
            get {
                return ResourceManager.GetString("MainForm_ResetLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver opciones..
        /// </summary>
        internal static string MainForm_ShowOptionsCheckBox {
            get {
                return ResourceManager.GetString("MainForm_ShowOptionsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar opciones..
        /// </summary>
        internal static string MainForm_ShowOptionsMainNotifyIconToolStripMenuItem {
            get {
                return ResourceManager.GetString("MainForm_ShowOptionsMainNotifyIconToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comenzar.
        /// </summary>
        internal static string MainForm_StartStopButton_Start {
            get {
                return ResourceManager.GetString("MainForm_StartStopButton_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar.
        /// </summary>
        internal static string MainForm_StartStopButton_Stop {
            get {
                return ResourceManager.GetString("MainForm_StartStopButton_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar señal para mantener el dispositivo activo..
        /// </summary>
        internal static string MainForm_StayAwakeCheckBox {
            get {
                return ResourceManager.GetString("MainForm_StayAwakeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar automáticamente después de:.
        /// </summary>
        internal static string MainForm_StopAutomaticallyCheckBox {
            get {
                return ResourceManager.GetString("MainForm_StopAutomaticallyCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H&apos;h&apos; mm&apos;m&apos; ss&apos;s&apos;.
        /// </summary>
        internal static string MainForm_TimeInputDateTimePicker {
            get {
                return ResourceManager.GetString("MainForm_TimeInputDateTimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cada (intervalo):.
        /// </summary>
        internal static string MainForm_TimeInputLabel {
            get {
                return ResourceManager.GetString("MainForm_TimeInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título de la aplicación:.
        /// </summary>
        internal static string MainForm_TitleLabel {
            get {
                return ResourceManager.GetString("MainForm_TitleLabel", resourceCulture);
            }
        }
    }
}
