//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adrenaline.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adrenaline.Strings.pt", typeof(pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adrenaline.
        /// </summary>
        internal static string MainForm {
            get {
                return ResourceManager.GetString("MainForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativado.
        /// </summary>
        internal static string MainForm_ActivatedMainNotifyIconToolStripMenuItem {
            get {
                return ResourceManager.GetString("MainForm_ActivatedMainNotifyIconToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string MainForm_ExitMainNotifyIconToolStripMenuItem {
            get {
                return ResourceManager.GetString("MainForm_ExitMainNotifyIconToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Entre com uma tecla].
        /// </summary>
        internal static string MainForm_KeyInputButton {
            get {
                return ResourceManager.GetString("MainForm_KeyInputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tecla a ser pressionada:.
        /// </summary>
        internal static string MainForm_KeyInputLabel {
            get {
                return ResourceManager.GetString("MainForm_KeyInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse aplicativo vai simular o pressionamento de uma tecla em seu teclado.
        ///
        ///Seu computador permanecerá ligado, e seus programas continuarão executando..
        /// </summary>
        internal static string MainForm_MainLabel {
            get {
                return ResourceManager.GetString("MainForm_MainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique duas vezes no ícone na bandeja do sistema para reabrir o aplicativo. Clique com o botão direito do mouse para ver mais ações..
        /// </summary>
        internal static string MainForm_MainNotifyIcon_BalloonTipText {
            get {
                return ResourceManager.GetString("MainForm_MainNotifyIcon_BalloonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitir um som de &quot;beep&quot;..
        /// </summary>
        internal static string MainForm_MakeSoundCheckBox {
            get {
                return ResourceManager.GetString("MainForm_MakeSoundCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aleatorizar intervalo em ±10%..
        /// </summary>
        internal static string MainForm_RandomIntervalCheckBox {
            get {
                return ResourceManager.GetString("MainForm_RandomIntervalCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (restaurar).
        /// </summary>
        internal static string MainForm_ResetLinkLabel {
            get {
                return ResourceManager.GetString("MainForm_ResetLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibir opções..
        /// </summary>
        internal static string MainForm_ShowOptionsCheckBox {
            get {
                return ResourceManager.GetString("MainForm_ShowOptionsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar opções.
        /// </summary>
        internal static string MainForm_ShowOptionsMainNotifyIconToolStripMenuItem {
            get {
                return ResourceManager.GetString("MainForm_ShowOptionsMainNotifyIconToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar.
        /// </summary>
        internal static string MainForm_StartStopButton_Start {
            get {
                return ResourceManager.GetString("MainForm_StartStopButton_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parar.
        /// </summary>
        internal static string MainForm_StartStopButton_Stop {
            get {
                return ResourceManager.GetString("MainForm_StartStopButton_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar sinal para manter dispositivo acordado..
        /// </summary>
        internal static string MainForm_StayAwakeCheckBox {
            get {
                return ResourceManager.GetString("MainForm_StayAwakeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H&apos;h&apos; mm&apos;m&apos; ss&apos;s&apos;.
        /// </summary>
        internal static string MainForm_TimeInputDateTimePicker {
            get {
                return ResourceManager.GetString("MainForm_TimeInputDateTimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cada (intervalo):.
        /// </summary>
        internal static string MainForm_TimeInputLabel {
            get {
                return ResourceManager.GetString("MainForm_TimeInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título do aplicativo:.
        /// </summary>
        internal static string MainForm_TitleLabel {
            get {
                return ResourceManager.GetString("MainForm_TitleLabel", resourceCulture);
            }
        }
    }
}
